apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::034777549885:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-InjuUhaxlrr0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::034777549885:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-14T09:42:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1205"
  uid: 77aed566-884f-45eb-9790-db43b31eb14d
